### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by SpeedrunnerG55** [tvincent056/linter-gcc2#4] opened 2019-01-16 17:20 UTC
[Enter steps to reproduce:]

1. make a change to repo
2. push change
3. switch to a different branch

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.1
**Thrown From**: [linter-gcc2](https://github.com/tvincent056/linter-gcc2) package 0.8.3

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /home/speed/.atom/packages/linter-gcc2/lib/utility.js:47

TypeError: Cannot read property 'file' of undefined
    at Object.getCwd (/packages/linter-gcc2/lib/utility.js:47:33)
    at Object.buildCommand (/packages/linter-gcc2/lib/utility.js:136:26)
    at Object.lint (/packages/linter-gcc2/lib/main.js:149:36)
    at /packages/linter-gcc2/lib/main.js:223:26
```

### Commands

```
     -1:55 gpp-compiler:compile (input.hidden-input)
     -0:52.5.0 intentions:highlight (input.hidden-input)
     -0:52.4.0 git-plus:copy (input.hidden-input)
     -0:52.4.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
arduino-upload 1.5.1 
atom-clock 0.1.16 
atom-python-run 0.9.7 
auto-copyright 0.6.0 
auto-indent 0.5.0 
autocomplete-clang 0.11.5 
autocomplete-computercraft 1.0.0 
busy-signal 2.0.0 
file-icons 2.1.28 
git-log 0.4.1 
git-plus 8.4.2 
git-time-machine 2.1.0 
glacier-dark-syntax 0.8.0 
glacier-dark-ui 1.5.0 
gpp-compiler 3.0.7 
highlight-selected 0.14.0 
intentions 1.1.5 
intentions-numbers 1.0.4 
language-arduino 0.4.3 
language-computercraft 0.2.1 
language-cuda 0.1.0 
language-d 3.3.1 
language-gitignore 0.3.0 
language-lua 0.9.11 
linter 2.3.0 
linter-gcc2 0.8.3 
linter-javac 1.9.4 
linter-nvcc 0.1.0 
linter-pylama 0.10.1 
linter-spell 0.15.0 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
pdf-view 0.71.0 
split-diff 1.5.4 
teletype 0.13.3 
tree-view-git-status 1.5.2 
wakatime 7.0.7 
```

**Comment by tvincent056** [comment] 2019-01-17 15:13
@SpeedrunnerG55 I wasn't able to reproduce your error, but I made some improvements to the part of the code referenced in the message. I committed the changes and pushed a new patch version 0.8.4. Let me know if this change solves your issue.

**Comment by tvincent056** [comment] 2019-02-24 19:25
It's been over a month since the patch so I'm going to assume that things went ok and close the issue.

**Closed by tvincent056** 2019-02-24 19:25 UTC
